version: "3"
services:
  oracle-xe:
    image: gvenzl/oracle-xe:21
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: MiPasswordSegura123
      APP_USER: myuser
      APP_USER_PASSWORD: MiPasswordUsuario123
    volumes:
      - oracle-xe-data:/opt/oracle/oradata
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mypguser
      POSTGRES_PASSWORD: MiPasswordPostgres123
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  oracle-xe-data:
  postgres-data:
